# 改用 Ctrl+A 作為 prefix
#unbind C-b
#set-option -g prefix C-a
#bind C-a send-prefix

#TODO: detect if terminal is iTerm2
#set -g default-terminal "tmux-256color" 

# 使用 vi 模式
setw -g mode-keys vi

# 啟用滑鼠
set -g mouse on

# 256 色支援
set -g default-terminal "screen-256color"

# 減少 escape 延遲
set -sg escape-time 0

# 視窗和 pane 從 1 開始編號
set -g base-index 1
set -g pane-base-index 1

# History length
set -g history-limit 10000

